---
# ConfigMap para configuración del frontend
apiVersion: v1
kind: ConfigMap
metadata:
  name: elcriollo-frontend-config
  namespace: elcriollo
data:
  # Configuración de la aplicación React
  REACT_APP_API_URL: "https://elcriolloapi.cjoga.cloud"
  REACT_APP_ENVIRONMENT: "production"
  REACT_APP_VERSION: "2.0.0"
  REACT_APP_BUILD_DATE: "2024-12-19"

---
# Deployment de El Criollo Frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elcriollo-frontend-deployment
  namespace: elcriollo
  labels:
    app: elcriollo-frontend
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: elcriollo-frontend
  template:
    metadata:
      labels:
        app: elcriollo-frontend
    spec:
      containers:
        - name: elcriollo-frontend
          image: cjoga/elcriollo-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          env:
            # Configuración desde ConfigMap
            - name: REACT_APP_API_URL
              valueFrom:
                configMapKeyRef:
                  name: elcriollo-frontend-config
                  key: REACT_APP_API_URL
            - name: REACT_APP_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: elcriollo-frontend-config
                  key: REACT_APP_ENVIRONMENT
            - name: REACT_APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: elcriollo-frontend-config
                  key: REACT_APP_VERSION
            - name: REACT_APP_BUILD_DATE
              valueFrom:
                configMapKeyRef:
                  name: elcriollo-frontend-config
                  key: REACT_APP_BUILD_DATE

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          # Configuración de seguridad
          securityContext:
            runAsNonRoot: true
            runAsUser: 101
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

      # Configuración de seguridad del pod
      securityContext:
        fsGroup: 101
        runAsNonRoot: true
        runAsUser: 101

      # Esperar a que la API esté disponible
      initContainers:
        - name: wait-for-api
          image: busybox:1.35
          imagePullPolicy: IfNotPresent
          command:
            - "sh"
            - "-c"
            - 'until wget --spider -q http://elcriollo-api-service/health; do echo "Esperando API..."; sleep 5; done; echo "API está disponible!"'

---
# Service para El Criollo Frontend
apiVersion: v1
kind: Service
metadata:
  name: elcriollo-frontend-service
  namespace: elcriollo
  labels:
    app: elcriollo-frontend
spec:
  selector:
    app: elcriollo-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  type: ClusterIP

---
# IngressRoute para acceso externo al frontend
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: elcriollo-frontend-ingress
  namespace: elcriollo
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`elcriollo.cjoga.cloud`)
      kind: Rule
      services:
        - name: elcriollo-frontend-service
          port: 80
      middlewares:
        - name: frontend-cors
          namespace: elcriollo

---
# Middleware para CORS del frontend
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: frontend-cors
  namespace: elcriollo
spec:
  headers:
    accessControlAllowOriginList:
      - "*"
    accessControlAllowMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
    accessControlAllowHeaders:
      - "*"
    accessControlExposeHeaders:
      - "*"
    accessControlAllowCredentials: true
    accessControlMaxAge: 86400
    # Configuración de seguridad adicional
    frameDeny: true
    contentTypeNosniff: true
    browserXssFilter: true
    referrerPolicy: "same-origin"
    contentSecurityPolicy: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://elcriolloapi.cjoga.cloud;"
